# Generated by Django 4.2.4 on 2023-08-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_images_imag_created_6393be_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='images_imag_created_d57897_idx',
        ),
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-total_likes'], name='images_imag_total_l_0bcd7e_idx'),
        ),
    ]
